package com.forum.jvcreader.utils;

import java.util.regex.Pattern;

public class PatternCollection
{
	public static final Pattern extractLoginCgiUrl = Pattern.compile("^cross_login\\.cgi\\?mode=user&pseudo=([^&]+)&t=([0-9]+)&k=(.+)$");
	public static final Pattern matchLoginFormatting = Pattern.compile("^[a-zA-Z0-9_\\-\\[\\]]{3,15}$");
	public static final Pattern matchPasswordFormatting = Pattern.compile("^[a-zA-Z0-9\\Q!#$%()*+,-./:;<=>?@[]^_`{|}~\\E]{4,32}$");
	public static final Pattern extractLoginCaptchaUrl = Pattern.compile("src=\"([^\"]+)\"");
	public static final Pattern fetchForumName = Pattern.compile("<h1 class=\"titre_forum\"><span class=\"txt\">Forum : </span>([^<]+)</h1>");
	public static final Pattern fetchForumJVName = Pattern.compile("<h3>Forum : <span>([^<]+)</span>");
	public static final Pattern fetchNextTopic = Pattern.compile("<tr class=\"tr([12])\">\n?<td><img src=\"[^\"]+?/(\\w+\\.gif)\" alt=\"\" /></td>\n?(?:<td><a href=\"([^\"]+)\" title=\"Supprimer ce message\"[^>]+><img[^>]+></a>\n?</td>\n?)?<td><a class=\"\\w+\" name=\"topic_([0-9]+)\"[^>]+>((?:[^<]+|<strong>[^<]+</strong>)+)</a></td>\n?<td class=\"pseudo ?(\\w*)\">([^<]+)</td>\n?<td>([0-9]+)</td>\n?<td>([/ 0-9h]+)</td>\n?</tr>");
	public static final Pattern fetchNextTopicReply = Pattern.compile("<tr class=\"tr([12])\">\n?<td>[^<]+</td>\n?<td class=\"rep\"><a class=\"[^\"]+\" href=\"([^\"]+)\">((?:[^<]+|<strong>[^<]+</strong>)+)</a></td>\n?<td class=\"pseudo([^\"]*)\">([^<]+)</td>");
	public static final Pattern extractTopicUrl = Pattern.compile("^.+/1-[0-9]+-([0-9]+)-([0-9]+).+#message_([0-9]+)$");
	public static final Pattern checkErrorMessage = Pattern.compile("<div class=\"form_err\">\n?<p class=\"alerte\">([^\u0007]+?)(?:<br />\n?)?</p>\n?</div>");
	public static final Pattern fetchTopicName = Pattern.compile("<h[14] class=\"sujet\"><span>Sujet : </span>\u00AB&#160;([^<]+?)&#160;\u00BB</h[14]>");
	public static final Pattern fetchNextPost = Pattern.compile("<div id=\"message_([0-9]+)\" class=\"msg msg([12])\">\n?<ul>\n?<li class=\"pseudo\">\n?(?:<a href=\"([^\"]+)\" title=\"Supprimer ce message\" onclick=\"(return confirmation)?[^>]+><[^>]+></a>\n?)?<strong([^>]+)?>([^<]+)</strong>\n?<a[^>]+><img[^>]+></a>\n?</li>\n?<li class=\"date\">Posté (<span>via mobile</span> )?le ?\n? ?([^<]+?)\n?(?:<a href=\"([^\"]+)\" title=\"Kicker[^>]+><img[^>]+></a>\n?)?(?:&#160;)?<a target=\"avertir\" rel=\"nofollow\" (?:title=\"Avertir un administrateur\" )?href=\"([^\"]+)\"[^>]+><img[^>]+></a></li>\n?<li class=\"post\">\n?((?:[^<]+|<img[^>]+>|<br />|<a[^>]+>[^<]+(?:<i>)?[^<]*(?:</i><span>)?[^<]*(?:</span>)?[^<]*</a>)+)</li>\n?(?:<li class=\"ancre\"><a href=\"([^\"]+)\">Lien permanent</a></li>\n?)?(?:<li class=\"suite_sujet\"><strong>([^<]+)<a href=\"([^\"]+)\">([^<]+)</a></strong></li>)?");
	public static final Pattern findReplyButton = Pattern.compile("<img src=\"[^\"]+?bt_forum_repondre.gif\"");
	public static final Pattern extractPageCount = Pattern.compile(">([0-9]+)</(a|strong)>( \\| <a href=\"[^\"]+\">\u00BB</a>)?</p>\n<table");
	public static final Pattern extractFormFieldset = Pattern.compile("name=\"post\" method=\"post\"[^>]+>\n?<fieldset>\n?([^\u0007]+?)\n?<div");
	public static final Pattern extractMobileFormFieldset = Pattern.compile("method=\"post\" name=\"post\" id=\"post\">\n<fieldset>\n([^\u0007]+?)\n<div>");
	public static final Pattern checkMobileErrorMessage = Pattern.compile("</strong></p>\n<ul>\n<li>([^\u0007]+?)</li>\n</ul>\n</div>");
	public static final Pattern extractMobileCaptchaData = Pattern.compile("<p id=\"captcha\">\n.+\n<input.*value=\"(.+?)\".*/>\n<img src=\"(.+?)\".*/>\n");
	public static final Pattern extractCaptchaData = Pattern.compile("<p class=\"confirm\">\n.+\n<input.*value=\"(.+?)\".*/>\n<img src=\"(.+?)\".*/>\n");
	public static final Pattern extractForumJVCaptchaData = Pattern.compile("<div class=\"code_confirm\">\n<label.+\n<input.*value=\"([a-zA-Z0-9]+)\".*/>\n<img src=\"(.+?)\".*/>");
	public static final Pattern fetchForumJVSearchFrame = Pattern.compile("</div><h1 id=\"resultat_forums\">(.+?)</h1>(?:<div class=\"bloc\" id=\"liste_rechforums\">\n<div class=\"bloc_inner\">\n<ul>\n([^\u0007]+?)</ul>)?");
	public static final Pattern fetchNextForumJVItem = Pattern.compile("<li><a href=\"http://([a-z0-9\\-]+)\\.forumjv\\.com/0-([0-9]+).*?htm\">(.+?)</a></li>\n");
	public static final Pattern fetchNextSmiley = Pattern.compile("\\s?(<img src=\".+?smileys_img/(.+?\\.(?:gif|png))\".*?>)\\s?");
	public static final Pattern fetchNextHtmlLink = Pattern.compile("<a href=\"(.+?)\".*?>(.+?)</a>");
	public static final Pattern fetchNextTextualSmiley = Pattern.compile("(:(question|cd|globe|malade|pacg|pacd|noel|(snif2?)|mac|gba|hap|nah|mort|(ouch2?)|content|nonnon|cool|sleep|doute|hello|honte|lol|(non2?)|monoeil|ok|oui|rechercher|(rire2?)|salut|sarcastic|up|peur|bye|dpdr|fou|gne|dehors|fier|coeur|rouge|sors|merci|svp|ange|diable|gni|spoiler|hs|desole|fete|sournois|hum|bravo|banzai|bave|hapoelparty|loveyou|cute|pf|play):|:((g|d|p)?\\)|o\\)\\)|-(p|D)|\\(|-\\(\\(?|-\\)|-\\)\\)\\)))([^\\(\\)]|$)");
	public static final Pattern fetchNextLink = Pattern.compile("https?://(.+?\\.)?.+?\\..+?/[^\\s]*");
	public static final Pattern fetchNextGame = Pattern.compile("<li><a href=\"(.+?)\">(.+?)</a>");
	public static final Pattern extractGameForumUrl = Pattern.compile("<li class=\"onglet_forum\"><span><a href=\"http://www.jeuxvideo.com/forums/0-([0-9]+)-.+?\">");
	public static final Pattern fetchNewMCFrame = Pattern.compile("<div id=\"new_mc\">\n([^\u0007]+?)</div>");
	public static final Pattern fetchNextNewMCGameFrame = Pattern.compile("<h4><img src=\".+?\" alt=\"(.+?)\"/></h4>\n<ul class=\"liste_liens on\">\n([^\u0007]+?)</ul>\n");
	public static final Pattern fetchOldMCFrame = Pattern.compile("<div id=\"old_mc\">\n([^\u0007]+?)</div>");
	public static final Pattern fetchNextOldMCGameFrame = Pattern.compile("<li><a href=\"#\"><img.*/> (.+?)</a>\n<ul class=\"liste_liens on\">\n([^\u0007]+?)</ul>\n</li>");
	public static final Pattern extractCDVBanInformation = Pattern.compile("<p class=\"banni\">(.+?)</p>");
	public static final Pattern fetchCDVMainPortlet = Pattern.compile("<div class=\"portlet\"><div id=\"(.+?)\">\n<div class=\"portlet-header\"><h2>(.+?)</h2></div>\n<div class=\"portlet-content\">\n([^\u0007]+?)<div id=\"(.+?)\">\n<div class=\"portlet-header\"><h2>(.+?)</h2></div>\n<div class=\"portlet-content\">\n([^\u0007]+?)</div></div>");
	public static final Pattern fetchNextCDVPortlet = Pattern.compile("<div class=\"portlet\" id=\"(.+?)\" ((style=\"display : none;\")?)>\n<div class=\"portlet-header\">\n?<h2>(.+?)</h2>\n?</div>\n<div class=\"portlet-content\">([^\u0007]+?)</div></div>");
	public static final Pattern fetchCDVContribPortlet1 = Pattern.compile("<div id=\"(pt_contribs_rec)\" class=\"portlet no_drag\">\n<div class=\"portlet-header\">\n?<h2>(.+?)</h2>\n?</div>\n<div class=\"portlet-content\">([^\u0007]+?)<div class=\"clearfix\"></div>");
	public static final Pattern fetchCDVContribPortlet2 = Pattern.compile("<div id=\"(pt_contribs_autres)\" class=\"portlet\">\n<div class=\"portlet-header\">\n?<h2>(.+?)</h2>\n?</div>\n<div class=\"portlet-content\">([^\u0007]+?)</div></div>");
	public static final Pattern extractCDVHeader = Pattern.compile("<h1 class=\"sexe_([mf])\">(?:<a.*?>)?(.+?)(?:</a>)?</h1>\n</li>\n<li id=\"rang\"><span>(.+?)</span></li>");
	public static final Pattern extractForumUrl = Pattern.compile("^(?:http://www\\.jeuxvideo\\.com)?(?:/forums)?/(0|1|3)-([0-9]+)-([0-9]+)-([0-9]+)-[0-9]+-([0-9]+)-([0-9]+)-(.+)\\.htm(?:#?message_([0-9]+))?$");
	public static final Pattern fetchNextDdbReason = Pattern.compile("<option  ?value=\"(.+?)\">(.+?)</option>");
	public static final Pattern extractDdbFormData = Pattern.compile("<input name=\"page\" id=\"page\" type=\"hidden\" value=\"([^\"]+)\" />\n?<input name=\"k\" id=\"k\" type=\"hidden\" value=\"([^\"]+)\" />\n?<input name=\"t\" id=\"t\" type=\"hidden\" value=\"([^\"]+)\" />(?:\n?<input name=\"session\" type=\"hidden\" value=\"([^\"]+)\" />\n?<input name=\"key\" type=\"hidden\" value=\"([^\"]+)\" />)?");
	public static final Pattern extractDdbCaptchaUrl = Pattern.compile("</label>\n<img src=\"(.+?)\"");
	public static final Pattern fetchDdbMessage = Pattern.compile("<p class=\"(?:alerte )?centrer\">([^\u0007]+?)</p>");
	public static final Pattern extractCdvUrl = Pattern.compile("^/profil/(.+?)\\.html$");
	public static final Pattern fetchNextPmTopic = Pattern.compile("<tr class=\"tr([12])\".*>\n<td class=\"(?:exp|dest)\">(<span class=\"admin\">)?(.+?)(?:</span>)?</td>\n<td class=\"sujet\"><a href=\".+?idd=([0-9]+).+?\"( class=\"lu\")?>(.+?)</a></td>\n<td class=\"date\">(.+?)</td>");
	public static final Pattern extractPmTopicListPageData = Pattern.compile("<td class=\"td2b\">Messages? <strong>([0-9]+)-([0-9]+)</strong> sur ([0-9]+)</td>");
	public static final Pattern extractPmTopicInfoMessage = Pattern.compile("<div class=\"info_page\"><p>(.+?)<p></div>");
	public static final Pattern extractPmTopicPreviousPostsCount = Pattern.compile("<div id=\"voir_debut\"><a href=\"#\">\\^.+?([0-9]+).+?\\^</a></div>");
	public static final Pattern fetchNextPmPost = Pattern.compile("(?:<div class=\"msg msg([12]).*?\".*?><ul>\n.+\n.+?src=\"(.+?)\" /></td>\n.+\n<li class=\"msg_header\">\n<span class=\"pseudo\"><strong>(<span class=\"admin\">)?(.+?)(?:</span>)?</strong> ?\n.+\n</span>\n<span class=\"msg_infos\">Post\u00E9 (<em>via mobile</em>)? ?le (.+?) <a.+href=\"(.+?)\".+/a>\n(?:.+\n)?</span></li>\n<li class=\"msg_body\">([^\u0007]*?)</li>\n</ul></div>)|(?:<div class=\"msg msg([12]).+?><ul>\n<li class=\"msg_header\">\n<span class=\"pseudo\"><strong>(.+?)</strong> ?\n.+\n(?:.+\n)?<span class=\"generic\">(.+?)</span>)");
	public static final Pattern extractPmTopicFieldset = Pattern.compile("<input id=\"control\".+value=\"(.+)\"/>\n<input id=\"tmp\".+value=\"([0-9]+)\"/>\n");
	public static final Pattern checkPmTopicErrorMessage = Pattern.compile("<div class=\"warning\">\n<p class=\"info\">.+</p>\n<ul>\n<li>(.+)</li>\n</ul>\n</div>");
	public static final Pattern extractPmTopicCaptchaData = Pattern.compile("<div class=\"code_confirm\">\n[^\u0007]+?<input.+name=\"signature\" value=\"(.+?)\".*\n<input.+name=\"clef\" value=\"(.+?)\".*\n<img src=\"(.+?)\"");
	public static final Pattern fetchPmTopicPseudosFrame = Pattern.compile("<div id=\"entre_pseudos\">([^\u0007]+?)</div>");
	public static final Pattern fetchNextPmTopicPseudo = Pattern.compile("<a href=\"(http://www\\.jeuxvideo\\.com/profil/.+?\\.html)\">(<span class=\"admin\">)?(.+?)(?:</span>)?</a>");
	public static final Pattern extractPmDdbFormData = Pattern.compile("name=\"id_message\".+?value=\"(.+?)\"[^\u0007]+?value=\"(.+?)\"[^\u0007]+?value=\"(.+?)\"");
	public static final Pattern findColorTagOnce = Pattern.compile("^(.*)\\{(.+?)\\}(.*)$");
	public static final Pattern extractPmNewFormData = Pattern.compile("<input id=\"control\" name=\"control\" type=\"hidden\" value=\"(.+?)\"/>\n<input id=\"tmp\" name=\"tmp\" type=\"hidden\" value=\"(.+?)\"/>");
	public static final Pattern extractPmTopicUrlFromNewPm = Pattern.compile("^/messages-prives/message\\.php\\?idd=(.+?)&box=2$");
	public static final Pattern checkTopicAdminControls = Pattern.compile("<a target=\"popup\" class=\"(de)?bloquer\" href=\"(.+?)\">.+\n(?:<a target=\"popup\" class=\"(de)?marquer\" href=\"(.+?)\">.+\n)?");
	public static final Pattern fetchKickFormError = Pattern.compile("<p class=\"erreur centrer\">(.+?)</p>");
	public static final Pattern extractKickFormData = Pattern.compile("<input type=\"hidden\" name=\"page\" value=\"(.+?)\" />\n<input type=\"hidden\" name=\"k\" value=\"(.+?)\" />");
	public static final Pattern fetchKickInterfaceUrl = Pattern.compile("<a href=\"([^\"]+)\" onclick=\"window\\.open\\('','kick_user'");
	public static final Pattern fetchTopicKickInterfaceUrl = Pattern.compile("<p class=\"lien_base\"><a href=\"(.+?)\".+>Voir l'interface de kick</a></p>");
	public static final Pattern extractPmTopicTimeKeyValues = Pattern.compile("<script type=\"text/javascript\">\n.+\n.+;var lo_time = ([0-9]+);var lo_cod = '(.+?)';");
	public static final Pattern extractKickInterfaceTotalKicks = Pattern.compile("<p class=\"lien_base\">Total : <strong>([0-9]+?)</strong> kicks</p>");
	public static final Pattern fetchNextKickInterfaceEntry = Pattern.compile("<tr class=\"tr[0-9]+\">\n<td><a.+?href=\"(.+?)\">.+?</td>\n<td>(.+?)</td>\n<td>(.+?)<br />.+?<p><strong>Sujet : </strong>([^\u0007]+?)</p><p><strong>Message : </strong>([^\u0007]+?)</p></div></td>\n<td>([0-9]+)</td>\n</tr>\n");
	public static final Pattern fetchNoelshackImageUrlData = Pattern.compile("^http://(?:www|image)\\.noelshack\\.com/(?:fichiers/)?([0-9]{4})(?:-|/)([0-9]{2})(?:-|/)(.+?)(\\.(jpe?g|gif|bmp|png))$", Pattern.CASE_INSENSITIVE);
	public static final Pattern fetchSuiteSujetClass = Pattern.compile("<li class=\"suite_sujet\"><strong>(.+?)<a href=\"(.+?)\">(.+?)</a></strong></li>");
	public static final Pattern fetchAlreadySentDdbReason = Pattern.compile("<input type=\"hidden\" name=\"motif\" value=\"([0-9]+)\"");
}